source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
# 引用框架
use_frameworks!
# ignore all warnings from all pods(注解)
inhibit_all_warnings!

def common_pods
  pod 'BTCaptchaView', :path => '../'
end

targets = ['BTCaptchaViewExample']
targets.each do |t|
  target t do
    common_pods
  end
end
